language: python
python: 2.7

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=pypy
    - env: TOX_ENV=pyflakes
    - env: TOX_ENV=manifest

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake g++-4.8 libstdc++-4.8-dev
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - echo "CXX=$CXX"
  - echo "version `$CXX --version`"
  - pip install pip --upgrade
  - pip install tox coveralls
  - git clone https://github.com/Mindwerks/worldengine-data.git ../worldengine-data

# # command to run tests
script:
  - tox -e $TOX_ENV

notifications:
    email: false

after_success:
    - coveralls